{{- if and .Values.telemetryWorker.enabled .Values.telemetryWorker.minAvailable }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "heavy-weather.fullname" . }}-telemetry-worker
  labels:
    {{- include "heavy-weather.labels" . | nindent 4 }}
    app.kubernetes.io/component: telemetry-worker
spec:
  minAvailable: {{ .Values.telemetryWorker.minAvailable }}
  selector:
    matchLabels:
      {{- include "heavy-weather.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: telemetry-worker
{{- end }}
