{{- if .Values.global.networkPolicy.defaultDeny }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "heavy-weather.fullname" . }}-default-deny-all
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "heavy-weather.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "heavy-weather.fullname" . }}-allow-dns-egress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "heavy-weather.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    {{- include "heavy-weather.dnsEgress" . | nindent 4 }}
{{- end }}
