{{- if .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secrets.name | default "ws-secrets" }}
  labels:
    {{- include "heavy-weather.labels" . | nindent 4 }}
type: Opaque
data:
  ADMIN_API_KEY: "c3VwZXItc2VjcmV0LWFkbWluLWtleQ=="
  POSTGRES_PASSWORD: "d3NfcGFzc3dvcmQ="
  WORKER_SHARED_SECRET: "bG9jYWwtd29ya2VyLXNlY3JldA=="
  POSTGRES_KC_PASSWORD: "d3Nfa2NfcGFzc3dvcmQK"
  COSMOS_KEY: "QzJ5NnlEamY1L1Irb2IwTjhBN0NndjMwVlJESklXRUhMTSs0UURVNURFMm5ROW5EdVZUcW9iRDRiOG1HR3lQTWJJWm5xeU1zRWNhR1F5NjdYSXcvSnc9PQ=="
{{- end }}
