/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "weather.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(proto_Histogram, proto_Histogram, AUTO)


PB_BIND(proto_DeviceInfo, proto_DeviceInfo, AUTO)


PB_BIND(proto_WeatherData, proto_WeatherData, AUTO)



