apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-server
  name: api-server
  namespace: weather-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  strategy: {}
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - image: ghcr.io/mkkl1/weather-station/hw-server@sha256:5aab2a230b9e6f926325cc3c67d18ab9807cc9728ca07a4b5f433e3f93f6f933
          name: api-server
          ports:
            - containerPort: 80
              name: http
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:80"
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: ws-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: ws-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ws-secrets
                  key: POSTGRES_PASSWORD
            - name: ConnectionStrings__PortainerConnection
              value: "Host=postgres-sv:5432;Database=$(POSTGRES_DB);Username=$(POSTGRES_USER);Password=$(POSTGRES_PASSWORD);"
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: ws-config
                  key: KEYCLOAK_REALM
            - name: Keycloak__Authority
              value: "http://keycloak:8080/realms/$(KEYCLOAK_REALM)"
            - name: COSMOS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: ws-config
                  key: COSMOS_ENDPOINT
            - name: COSMOS_KEY #TODO this should be secret
              valueFrom:
                configMapKeyRef:
                  name: ws-config
                  key: COSMOS_KEY
            - name: CosmosDb__ConnectionString
              value: "AccountEndpoint=$(COSMOS_ENDPOINT);AccountKey=$(COSMOS_KEY)"
            - name: CosmosDb__DatabaseName
              valueFrom:
                configMapKeyRef:
                  name: ws-config
                  key: COSMOS_DATABASE
            - name: CosmosDb__ViewsContainerName
              valueFrom:
                configMapKeyRef:
                  name: ws-config
                  key: COSMOS_CONTAINER_VIEWS
            - name: COSMOS_TLS_INSECURE
              valueFrom:
                configMapKeyRef:
                  name: ws-config
                  key: COSMOS_TLS_INSECURE
            - name: AuthService__BaseUrl
              value: "http://provisioning-sv:80/api/v1/devices/"
            - name: AuthService__SharedSecret
              valueFrom:
                secretKeyRef:
                  name: ws-secrets
                  key: WORKER_SHARED_SECRET
            - name: AdminApiKey__ApiKey
              valueFrom:
                secretKeyRef:
                  name: ws-secrets
                  key: ADMIN_API_KEY
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apiserver-sv
  name: apiserver-sv
  namespace: weather-app-dev
spec:
  ports:
    - name: 80-80
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: api-server
  type: ClusterIP
status:
  loadBalancer: {}
