apiVersion: batch/v1
kind: Job
metadata:
  name: weather-db-migration
  namespace: weather-app-dev
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migration-runner
          image: ghcr.io/mkkl1/weather-station/hw-server:test
          imagePullPolicy: Never
          command: ["./WeatherStation.API"]
          args: ["--migrate"]
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: ws-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: ws-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ws-secrets
                  key: POSTGRES_PASSWORD
            - name: Postgres__ConnectionString
              value: "Host=postgres-sv;Port=5432;Database=$(POSTGRES_DB);Username=$(POSTGRES_USER);Password=$(POSTGRES_PASSWORD);"
