apiVersion: v1
data:
  ADMIN_API_KEY: c3VwZXItc2VjcmV0LWFkbWluLWtleQ==
  POSTGRES_PASSWORD: d3NfcGFzc3dvcmQ=
  WORKER_SHARED_SECRET: bG9jYWwtd29ya2VyLXNlY3JldA==
  POSTGRES_KC_PASSWORD: d3Nfa2NfcGFzc3dvcmQK
kind: Secret
metadata:
  name: ws-secrets
  namespace: weather-app-dev
