apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: telemetry-worker
  name: telemetry-worker
  namespace: weather-app-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: telemetry-worker
  strategy: {}
  template:
    metadata:
      labels:
        app: telemetry-worker
    spec:
      initContainers:
        - name: wait-for-azurite
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z -v -w3 azurite-sv 10000; do
                echo "Waiting for Azurite Storage Emulator to spin up..."
                sleep 2
              done
              echo "Azurite is UP!"
      containers:
        - image: ghcr.io/mkkl1/weather-station/hw-telemetry-worker@sha256:02158d122f9a2b8dfdb26b8b99c3e307ffa0f9bf554eaba73295a416dbd1f945
          name: hw-telemetry-worker
          env:
            - name: AZURITE_ACCOUNT
              valueFrom:
                configMapKeyRef:
                  name: ws-config
                  key: AZURITE_ACCOUNT
            - name: AZURITE_KEY
              valueFrom:
                configMapKeyRef:
                  name: ws-config
                  key: AZURITE_KEY
            - name: COSMOS_ENDPOINT
              value: http://cosmos-sv:8081
            - name: COSMOS_KEY
              valueFrom:
                configMapKeyRef:
                  name: ws-config
                  key: COSMOS_KEY
            - name: FUNCTIONS_WORKER_RUNTIME
              value: "dotnet-isolated"
            - name: AzureWebJobsStorage
              value: "DefaultEndpointsProtocol=http;AccountName=$(AZURITE_ACCOUNT);AccountKey=$(AZURITE_KEY);BlobEndpoint=http://azurite-sv:10000/$(AZURITE_ACCOUNT);QueueEndpoint=http://azurite-sv:10001/$(AZURITE_ACCOUNT);TableEndpoint=http://azurite-sv:10002/$(AZURITE_ACCOUNT)"
            - name: COSMOS_CONNECTION
              value: "AccountEndpoint=$(COSMOS_ENDPOINT);AccountKey=$(COSMOS_KEY)"
            - name: COSMOS_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: ws-config
                  key: COSMOS_DATABASE
            - name: COSMOS_CONTAINER
              valueFrom:
                configMapKeyRef:
                  name: ws-config
                  key: COSMOS_CONTAINER_REGISTRY
            - name: COSMOS_VIEWS_CONTAINER
              valueFrom:
                configMapKeyRef:
                  name: ws-config
                  key: COSMOS_CONTAINER_VIEWS
            - name: COSMOS_TELEMETRY_CONTAINER
              valueFrom:
                configMapKeyRef:
                  name: ws-config
                  key: COSMOS_CONTAINER_TELEMETRY
            - name: COSMOS_TLS_INSECURE
              valueFrom:
                configMapKeyRef:
                  name: ws-config
                  key: COSMOS_TLS_INSECURE
          ports:
            - containerPort: 80
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: telemetry-worker-sv
  name: telemetry-worker-sv
spec:
  ports:
    - name: 80-80
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: telemetry-worker
  type: ClusterIP
status:
  loadBalancer: {}
