API_PATH_REGISTER = "/provisioning/register"
API_PATH_TOKEN = "/device/auth/token"
API_PATH_TELEMETRY = "/device/telemetry"

BASE_TEMP_C = 20.0
BASE_PRESSURE_HPA = 1013.25
BASE_HUMIDITY_PERCENT = 50.0

RAIN_PROBABILITY_FACTOR = 0.3
DEFAULT_BUCKET_SECONDS = 120
DEFAULT_NUM_BUCKETS = 5

TOKEN_REFRESH_BUFFER_SEC = 60
TOKEN_DEFAULT_TTL_SEC = 86400