{{- if and .Values.provisioning.enabled .Values.provisioning.minAvailable }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "heavy-weather.fullname" . }}-provisioning
  labels:
    {{- include "heavy-weather.labels" . | nindent 4 }}
    app.kubernetes.io/component: provisioning
spec:
  minAvailable: {{ .Values.provisioning.minAvailable }}
  selector:
    matchLabels:
      {{- include "heavy-weather.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: provisioning
{{- end }}
