name: Publish IoTEventWorker on tag

on:
  push:
    tags:
      - 'func-v*'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'deploy/IoTEventWorker'
  DOTNET_VERSION: '8.0.x'
  DOTNET_PROJECT_PATH: 'deploy/IoTEventWorker/Worker/Worker.csproj'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: production

    steps:
      - name: Checkout the tag
        uses: actions/checkout@v5

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Build and Publish Project'
        shell: bash
        run: |
          dotnet publish "${{ env.DOTNET_PROJECT_PATH }}" --configuration Release --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output"

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'fn-weather-station-dev'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'